apiVersion: apps/v1
kind: Deployment
metadata:
  name: driver-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: driver-service
  template:
    metadata:
      labels:
        app: driver-service
    spec:
      containers:
        - name: driver-service
          image: IMAGE_PLACEHOLDER/driver-service
          ports:
            - name: grpc
              containerPort: 9092
            - name: http
              containerPort: 8082
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          env:
            - name: RABBITMQ_URI
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: uri
            - name: REDIS_URI
              valueFrom:
                configMapKeyRef:
                  key: REDIS_URI
                  name: app-config
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  key: OTEL_EXPORTER_OTLP_ENDPOINT
                  name: app-config
---
apiVersion: v1
kind: Service
metadata:
  name: driver-service
spec:
  selector:
    app: driver-service
  ports:
    - name: grpc
      port: 9092
      targetPort: 9092
    - name: http
      port: 8082
      targetPort: 8082
  type: ClusterIP
