apiVersion: external-secrets.io/v1
kind: ExternalSecret # this is the ExternalSecret resource that defines how to fetch secrets from AWS Secrets Manager and create Kubernetes secrets
metadata:
  name: rabbitmq-credentials
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: rabbitmq-credentials
    creationPolicy: Owner
  data:
    - secretKey: uri
      remoteRef:
        key: ride-go-mcs/prod/rabbitmq
        property: uri
    - secretKey: username
      remoteRef:
        key: ride-go-mcs/prod/rabbitmq
        property: username
    - secretKey: password
      remoteRef:
        key: ride-go-mcs/prod/rabbitmq
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: stripe-secrets
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: stripe-secrets
    creationPolicy: Owner
  data:
    - secretKey: stripe-publishable-key
      remoteRef:
        key: ride-go-mcs/prod/stripe
        property: stripe-publishable-key
    - secretKey: stripe-secret-key
      remoteRef:
        key: ride-go-mcs/prod/stripe
        property: stripe-secret-key
    - secretKey: stripe-webhook-key
      remoteRef:
        key: ride-go-mcs/prod/stripe
        property: stripe-webhook-key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-credentials
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: postgres-credentials
    creationPolicy: Owner
  data:
    - secretKey: host
      remoteRef:
        key: ride-go-mcs/prod/postgres
        property: host
    - secretKey: port
      remoteRef:
        key: ride-go-mcs/prod/postgres
        property: port
    - secretKey: username
      remoteRef:
        key: ride-go-mcs/prod/postgres
        property: username
    - secretKey: password
      remoteRef:
        key: ride-go-mcs/prod/postgres
        property: password
    - secretKey: database
      remoteRef:
        key: ride-go-mcs/prod/postgres
        property: database
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jwt-secrets
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: jwt-secrets
    creationPolicy: Owner
  data:
    - secretKey: secret
      remoteRef:
        key: ride-go-mcs/prod/jwt
        property: secret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: google-auth-secrets
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: google-auth-secrets
    creationPolicy: Owner
  data:
    - secretKey: client-id
      remoteRef:
        key: ride-go-mcs/prod/google-auth
        property: client-id
    - secretKey: client-secret
      remoteRef:
        key: ride-go-mcs/prod/google-auth
        property: client-secret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mongodb
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: mongodb
    creationPolicy: Owner
  data:
    - secretKey: uri
      remoteRef:
        key: ride-go-mcs/prod/mongodb
        property: uri
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mongo-credentials
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: mongo-credentials
    creationPolicy: Owner
  data:
    - secretKey: uri
      remoteRef:
        key: ride-go-mcs/prod/mongodb
        property: uri
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextauth-secrets
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: nextauth-secrets
    creationPolicy: Owner
  data:
    - secretKey: nextauth-secret
      remoteRef:
        key: ride-go-mcs/prod/nextauth
        property: nextauth-secret
