apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ride-sharing-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-south-1:326306381458:certificate/e81beb22-f175-4cfa-8b34-d5f4923c8e5b # this should be replaced with the actual ACM certificate ARN for your domain
spec:
  rules:
    - host: app.rexy.co.in
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 3000
    - host: api.rexy.co.in
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 8081
    - host: ws.rexy.co.in
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ws-gateway
                port:
                  number: 8082
