apiVersion: external-secrets.io/v1
kind: SecretStore # this is the SecretStore resource that defines how to authenticate with AWS Secrets Manager and fetch secrets
metadata:
  name: aws-secretsmanager
  namespace: default
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-south-1
      role: arn:aws:iam::326306381458:role/external-secrets-read-ride-go-mcs-prod
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
