apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secretsmanager
  namespace: default
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-south-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: default
# this tells ESO to use the AWS credentials from the 'external-secrets' service account, which should have the necessary IAM permissions to access Secrets Manager