apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: otel-collector-agent
  namespace: default
spec:
  selector:
    matchLabels:
      app: otel-collector-agent
  template:
    metadata:
      labels:
        app: otel-collector-agent
    spec:
      containers:
        - name: otel-collector-agent
          image: otel/opentelemetry-collector-contrib:0.102.1
          args:
            - --config=/etc/otelcol/collector-agent.yaml
          startupProbe:
            httpGet:
              path: /
              port: 13133
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 12
          readinessProbe:
            httpGet:
              path: /
              port: 13133
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 13133
            initialDelaySeconds: 10
            periodSeconds: 15
            timeoutSeconds: 2
            failureThreshold: 3
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          volumeMounts:
            - name: otel-collector-agent-config
              mountPath: /etc/otelcol
            - name: varlogpods
              mountPath: /var/log/pods
              readOnly: true
      volumes:
        - name: otel-collector-agent-config
          configMap:
            name: otel-collector-agent-config
        - name: varlogpods
          hostPath:
            path: /var/log/pods
            type: DirectoryOrCreate
