apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-agent-config
  namespace: default
data:
  collector-agent.yaml: |
    receivers:
      filelog:
        include:
          - /var/log/pods/*/*/*.log
        exclude:
          - /var/log/pods/*/otel-collector-agent/*.log
          - /var/log/pods/*/otel-collector-gateway/*.log
        start_at: end
        include_file_path: true

    processors:
      batch:
        send_batch_size: 1024
        timeout: 5s
      memory_limiter:
        check_interval: 5s
        limit_mib: 128
        spike_limit_mib: 32

    exporters:
      otlp:
        endpoint: otel-collector:4317
        tls:
          insecure: true

    extensions:
      health_check:
        endpoint: 0.0.0.0:13133

    service:
      extensions: [health_check]
      pipelines:
        logs:
          receivers: [filelog]
          processors: [memory_limiter, batch]
          exporters: [otlp]
