apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dlq-worker.fullname" . }}
  labels:
    {{- include "dlq-worker.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "dlq-worker.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "dlq-worker.fullname" . }}
    spec:
      containers:
        - name: dlq-worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          envFrom:
            - configMapRef:
                name: {{ .Values.env.configMapName }}
            - secretRef:
                name: {{ .Values.env.secretName }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /readyz
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 15
            periodSeconds: 20
