{{- if .Values.migration.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "api-gateway.fullname" . }}-migration
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migration
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command:
            {{- toYaml .Values.migration.command | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ .Values.env.configMapName }}
            - secretRef:
                name: {{ .Values.env.secretName }}
{{- end }}
