apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      containers:
        - name: chat-service
          image: ride-sharing/chat-service
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          env:
            - name: RABBITMQ_URI
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: uri
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: uri
            - name: MONGO_DB
              value: "chat"
            - name: JAEGER_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  key: JAEGER_ENDPOINT
                  name: app-config
