apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.env.configMapName }}
data:
  {{- if .Values.configMap }}
  {{- toYaml .Values.configMap | nindent 2 }}
  {{- else }}
  # Add configuration here
  APP_PORT: "{{ .Values.service.targetPort }}"
  {{- end }}
