apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.env.secretName }}
type: Opaque
data:
  {{- if .Values.secrets }}
  {{- toYaml .Values.secrets | nindent 2 }}
  {{- else }}
  # Add secrets here - encode values in base64
  {{- end }}
